block_group_shapefile_path: block_group/tl_2020_24_tabblock20.shp
rac_file_path: md_rac_S000_JT00_2020.csv.gz
wac_file_path: md_wac_S000_JT00_2020.csv.gz
osm_path: maryland-latest.osm.pbf

bus_accurate_csv: bus_accurate_data.csv
begin_date: 2023-01-01
end_date: 2023-02-07
begin_hour: 8
end_hour: 10

api_key: T2Jljq0EQqqe1JMfijkn3RdtVxoYpwuq
bus_feed_link: 8523f088e05dcd273b369dd4d65eb771c73c0a22
rail_feed_link: c4233b29806296fc80209881fd9cec6c49fd9380
subway_feed_link: 9b0a275f899fcb67a9d2107be8b9976326507a35
commuterbus_feed_link: 6cc96d82827a3dfb39807521ad8a77cf8d77b368
train_feed_link: 32c1ab0bebce48f0f58a8110ebe245ccb5008930

raw_data_path: raw_data/
processed_data_path: processed_data/
transitland_path: transitland/
stop_times_path: stop_times.txt

period: 8
speed: 20
early_time: 7
late_time: 10


